<?php
/**
 *  This file part is part of amfPHP
 *
 * LICENSE
 *
 * This source file is subject to the license that is bundled
 * with this package in the file license.txt.
 */


require_once dirname(__FILE__) . '/../../../../Amfphp/Plugins/AmfphpLogger/AmfphpLogger.php';
require_once dirname(__FILE__) . '/../../../../Amfphp/ClassLoader.php';

/**
 * Test class for AmfphpLogger.
 * Generated by PHPUnit on 2011-01-13 at 17:28:26.
 */
class AmfphpLoggerTest extends PHPUnit_Framework_TestCase {

    public function testSimple(){
        $logger = new AmfphpLogger();
        //delete the log file if it exists to make sure it's empty when we write to it
        try{
            unlink(AmfphpLogger::LOG_FILE_PATH);
        }catch(Exception $e){}
        $logger->requestSerializedHandler("bla");
        $logFileContent = file_get_contents(AmfphpLogger::LOG_FILE_PATH);
        //clean up
        unlink(AmfphpLogger::LOG_FILE_PATH);
        
        $this->assertEquals("serialized request : \nbla\n", $logFileContent);
    }

}

?>
