<?php

require_once dirname(__FILE__) . '/../../../../amfphp/AMFPHPClassLoader.php';

/**
 * Test class for ServiceCallParameters.
 * Generated by PHPUnit on 2011-01-06 at 11:37:48.
 */
class ServiceCallParametersTest extends PHPUnit_Framework_TestCase {


    public function testCreateFromAMFMessage() {
        $amfMessage = new AMFMessage("serviceFolder.service/serviceMethod", "/1", array("bla"));
        $serviceCallParameters = ServiceCallParameters::createFromAMFMessage($amfMessage);
        $this->assertEquals("serviceFolder/service" , $serviceCallParameters->serviceName);
        $this->assertEquals("serviceMethod" , $serviceCallParameters->methodName);
        $this->assertEquals(array("bla") , $serviceCallParameters->methodParameters);
    }

}

?>
