<?php

require_once dirname(__FILE__) . '/../../../../amfphp/AMFPHPClassLoader.php';

/**
 * Test class for Amfphp_Core_Common_ServiceCallParameters.
 * Generated by PHPUnit on 2011-01-06 at 11:37:48.
 */
class Amfphp_Core_Common_ServiceCallParametersTest extends PHPUnit_Framework_TestCase {


    public function testCreateFromAmfphp_Core_Amf_Message() {
        $Amfphp_Core_Amf_Message = new Amfphp_Core_Amf_Message("serviceFolder.service/serviceMethod", "/1", array("bla"));
        $Amfphp_Core_Common_ServiceCallParameters = Amfphp_Core_Common_ServiceCallParameters::createFromAmfphp_Core_Amf_Message($Amfphp_Core_Amf_Message);
        $this->assertEquals("serviceFolder/service" , $Amfphp_Core_Common_ServiceCallParameters->serviceName);
        $this->assertEquals("serviceMethod" , $Amfphp_Core_Common_ServiceCallParameters->methodName);
        $this->assertEquals(array("bla") , $Amfphp_Core_Common_ServiceCallParameters->methodParameters);
    }

}

?>
