<?php

require_once dirname(__FILE__) . '/../../../../amfphp/ClassLoader.php';
require_once dirname(__FILE__) . "/../../../testData/TestServicesConfig.php";

/**
 * Test class for DefaultServiceRouter.
 * Generated by PHPUnit on 2010-11-26 at 16:50:22.
 */
class ServiceRouterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var DefaultServiceRouter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $testServiceConfig = new TestServicesConfig();
        $this->object = new ServiceRouter($testServiceConfig->serviceFolderPaths, $testServiceConfig->serviceNames2ClassFilePath);
    }

    public function testExecuteMirrorServiceCall(){
        $testParamsArray = array("a", "b", "c");
        $mirrored = $this->object->executeServiceCall("MirrorService", "mirrorFunction", $testParamsArray);
        $this->assertEquals($mirrored, $testParamsArray);
    }

    public function testFindDummyServiceInFolder(){
        $ret = $this->object->executeServiceCall("DummyService", "returnNull", array());
        $this->assertEquals($ret, null);
    }

     /**
     * @expectedException Exception
     */
    public function testNoServiceException()
    {
        $ret = $this->object->executeServiceCall("NoService", "noFunction", array());
    }

     /**
     * @expectedException Exception
     */
    public function testNoFunctionException()
    {
        $ret = $this->object->executeServiceCall("DummyService", "noFunction", array());
        $this->assertEquals($ret, null);
    }
}

?>
