<?php

require_once dirname(__FILE__) . '/../../../Amfphp/plugins/AMFPHPLogger.php';
require_once dirname(__FILE__) . '/../../../Amfphp/ClassLoader.php';

/**
 * Test class for AMFPHPLogger.
 * Generated by PHPUnit on 2011-01-13 at 17:28:26.
 */
class AMFPHPLoggerTest extends PHPUnit_Framework_TestCase {

    public function testSimple(){
        $logger = new AMFPHPLogger();
        //delete the log file if it exists to make sure it's empty when we write to it
        try{
            unlink(AMFPHPLogger::LOG_FILE_PATH);
        }catch(Exception $e){}
        $logger->packetRequestSerializedHandler("bla");
        $logFileContent = file_get_contents(AMFPHPLogger::LOG_FILE_PATH);
        //clean up
        unlink(AMFPHPLogger::LOG_FILE_PATH);
        
        $this->assertEquals("serialized request packet : \nbla\n", $logFileContent);
    }

}

?>
