<?php

require_once dirname(__FILE__) . '/../../../../Amfphp/ClassLoader.php';

/**
 * Test class for Amfphp_Core_Amf_Util.
 * Generated by PHPUnit on 2011-01-20 at 15:43:40.
 */
class Amfphp_Core_Amf_UtilTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Amfphp_Core_Amf_Util
     */
    protected $object;
    /**
     * for testApplyFunc
     * @var int
     */
    private $counter;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Amfphp_Core_Amf_Util;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    public function testIsSystemBigEndian() {
        $isBigEndian = Amfphp_Core_Amf_Util::isSystemBigEndian();
        $this->assertTrue(($isBigEndian == false) || ($isBigEndian == true));
    }

    public function testGetRawPostData() {
        $this->assertTrue(Amfphp_Core_Amf_Util::getRawPostData() == null);
    }

    public function testApplyFunc($obj = null){
        $this->counter++;
        return $obj;
    }

    public function testApplyFunctionToContainedObjects() {
        //simple
        $testObj1 = array();
        $testObj1[] = new stdClass();
        $this->counter = 0;
        Amfphp_Core_Amf_Util::applyFunctionToContainedObjects($testObj1, array($this, "testApplyFunc"), 0, 10);
        $this->assertEquals(2, $this->counter);

        //a bit more complicated
        $testObj2 = new stdClass();
        $subObj = array(new stdClass(), new stdClass(), array(1, 2, false), null);
        $testObj2->data = $subObj;
        $testObj2->bla = 'bla';
        $this->counter = 0;
        Amfphp_Core_Amf_Util::applyFunctionToContainedObjects($testObj2, array($this, "testApplyFunc"), 0, 10);
        $this->assertEquals(10, $this->counter);

    }

}

?>
