<?php

require_once dirname(__FILE__) . '/../../../Amfphp/ClassLoader.php';

/**
 * Test class for Amfphp_Core_HookManager.
 * Generated by PHPUnit on 2011-01-13 at 15:51:00.
 * @todo reenable tests
 */
class Amfphp_Core_HookManagerTest extends PHPUnit_Framework_TestCase {
    public function testHook() {
        $hookManager = Amfphp_Core_HookManager::getInstance();
        //add the same hook twice to test filtering
        $hookManager->addHook("TESTHOOK", $this, "double");
        $hookManager->addHook("TESTHOOK", $this, "double");

        $ret = $hookManager->callHooks("TESTHOOK", 1);
        $this->assertEquals(4, $ret);


    }

    /**
     * note: this function must be public to be called. This is called by hook
     * @param <type> $valueToDouble
     * @return <type>
     */
    public function double($valueToDouble){
        return $valueToDouble * 2;
    }

}

?>
