<?php

require_once dirname(__FILE__) . '/../../../Amfphp/ClassLoader.php';

/**
 * Test class for Amfphp_Core_HookManager.
 * Generated by PHPUnit on 2011-01-13 at 15:51:00.
 * @todo reenable tests
 */
class Amfphp_Core_HookManagerTest extends PHPUnit_Framework_TestCase {
    public function testHook() {
        $hookManager = Amfphp_Core_HookManager::getInstance();
        //add the same hook twice to test filtering
        $hookManager->addHook("TESTHOOK", array($this, "double"));
        $hookManager->addHook("TESTHOOK", array($this, "double"));
        return;

        $ret = $hookManager->callHooks("TESTHOOK", array(1), Amfphp_Core_HookManager::BEHAVIOR_GETTER);
        $this->assertEquals(2, $ret);
        $ret = $hookManager->callHooks("TESTHOOK", array(1), Amfphp_Core_HookManager::BEHAVIOR_FILTER);
        $this->assertEquals(4, $ret);
        $ret = $hookManager->callHooks("TESTHOOK", array(1), Amfphp_Core_HookManager::BEHAVIOR_GIVER);
        $this->assertEquals(null, $ret);


    }

    /**
     * note: this function must be public to be called. This is called by hook
     * @param <type> $valueToDouble
     * @return <type>
     */
    public function double($valueToDouble){
        return $valueToDouble * 2;
    }

}

?>
